### ISSUE TITLE
Analyse error when trying to instal.

### ISSUE THREAD

**Issue by Icesenator** [bpear96/Magisk-Quick-Toggle#2]
![screenshot_20160916-071825](https://cloud.githubusercontent.com/assets/17598875/18576036/ef4283e0-7bdd-11e6-8c68-ba5ba1ed2245.jpg)

**Comment by medsouz** [comment]
> Parsing error
> 
> A problem occurred during the Package Analysis

Are you on Android N?

**Comment by Icesenator** [comment]
Android M on ZE551ML

**Comment by medsouz** [comment]
This app requires Android N's new quick settings API. It won't work on Android M.

**Comment by Icesenator** [comment]
Oh okay my bad.

**Comment by bpear** [comment]
I should make it more clear that this only works on Android N. I may allow it to be installed on earlier versions but prompt with a notification saying the app is not compatible to avoid this confusion.
